#!/usr/bin/env bash

set -e

(which kubectl &>/dev/null) || (echo '* missing kubectl, is it installed?' && exit 1)
(kubectl get nodes &>/dev/null) || (echo '* kubectl cannot contact cluster, is it setup correctly?' && exit 1)

while (kubectl get pods 2>&1 | grep '0/\|1/2\|No resources') &>/dev/null; do
    sleep 1
done
